### ISSUE TITLE
[Sat Dec 05 22:40:09.529323 2015] [:error] [pid 31534] [client 141.101.75.53:27377] PHP Fatal error:  Call to undefined method OC_L10N::forceLanguage() in /var/www/owncloud/apps/agreedisclaimer/appinfo/application.php on line 175

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [jmeile/agreedisclaimer#18]
Hey jmeile, thanks again for the great app. Using it quite some time now, but i just found out this error, which breaks owncloud in chrome but not on firefox for me (ubuntu). Also chrome and firefox on android cant display owncloud with the app enabled.

owncloud 8.2.1
Apache2 latest
php latest

visiting my owncloud on chrome gives me a internal error 500 and apache logs show:

[Sat Dec 05 22:40:09.529323 2015] [:error] [pid 31534] [client 141.101.75.53:27377] PHP Fatal error:  Call to undefined method OC_L10N::forceLanguage() in /var/www/owncloud/apps/agreedisclaimer/appinfo/application.php on line 175

owncloud logs show nothing.

Hope you can help! thanks alot!

**Comment by jmeile** [comment]
Hi

When do you get the error? On the login page or once you are authenticated?

**Comment by WaaromZoMoeilijk** [comment]
Login page! Also this app enabled breaks the android ownnote app, i think
because the app cant get past the checkbox?

Regards Ezra

Op zo 6 dec. 2015 11:32 schreef Josef Meile notifications@github.com:

> Hi
> 
> When do you get the error? On the login page or once you are authenticated?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jmeile/agreedisclaimer/issues/18#issuecomment-162299064
> .
> 
> ## 

Met vriendelijke groet,

E. Holm

**Comment by WaaromZoMoeilijk** [comment]
Anyone knows how to fix this? I really dont want to use the other agree disclaimer of owncloud, just not as good as this one!

**Comment by jmeile** [comment]
Sorry, I didn't have much time to look at it. I will try to do it next week.

**Comment by jmeile** [comment]
Dear  ezraholm50

The problem is that owncloud 8.2.1 dropped the function: forceLanguage

I really don't know how to replace it on my code, so, I posted a message on the list:
https://mailman.owncloud.org/pipermail/devel/2015-December/001791.html

On the while, I remove that call on the release 2.0.0:
https://github.com/jmeile/agreedisclaimer/archive/2.0.0.zip

The only problem is that if somebody, let's say with Russian on his browser comes, then you will see the main owncloud dialog in russian, but the rest of the AgreeDisclaimer will be displayed in English. This is because AgreeDisclaimer doesn't have all the languages that owncloud has, so, it will fallback to English, German, Spanish, or English.

I think this can be solved, but I will wait for an official solution.

Best regards
Josef

**Comment by WaaromZoMoeilijk** [comment]
Dear Josef,

Thank younso much for looking into this! I will wait for the fix and gladly
use your app again.

Also what about the appcodechecker? Doesnt allow me to use your app, and it
also breaks the ownnote app, same error as you mentioned? If you need any
help (not coding wise) let me know.

Kind regards,

Ezra Holm

Op za 12 dec. 2015 12:49 schreef Josef Meile notifications@github.com:

> Dear ezraholm50
> 
> The problem is that owncloud 8.2.1 dropped the function: forceLanguage
> 
> I really don't know how to replace it on my code, so, I posted a message
> on the list:
> https://mailman.owncloud.org/pipermail/devel/2015-December/001791.html
> 
> On the while, I remove that call on the release 2.0.0:
> https://github.com/jmeile/agreedisclaimer/archive/2.0.0.zip
> 
> The only problem is that if somebody, let's say with Russian on his
> browser comes, then you will see the main owncloud dialog in russian, but
> the rest of the AgreeDisclaimer will be displayed in English. This is
> because AgreeDisclaimer doesn't have all the languages that owncloud has,
> so, it will fallback to English, German, Spanish, or English.
> 
> I think this can be solved, but I will wait for an official solution.
> 
> Best regards
> 
> Josef
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jmeile/agreedisclaimer/issues/18#issuecomment-164141274
> .
> 
> ## 

Met vriendelijke groet,

E. Holm

**Comment by WaaromZoMoeilijk** [comment]
2.0 fixed it for me thanks!!! Any idea on how to fix ownnote android login because of the check box it cant login.

It uses the owncloud base url and no remote.php url. Thanks again for thid great app.

Kind regards,
Ezra
