### ISSUE TITLE
dav sync error

### ISSUE THREAD

**Issue by ezraholm50** [jmeile/agreedisclaimer#7]
Hey! Hows the update coming along? Great work mate! I noticed that my android caldav and card dav cant sync when the app in enabled cause of an authorisation error, could you look into this?

Kind regards,

Ezra

**Comment by jmeile** [comment]
Fixed on branch: 0.1.1:
https://github.com/jmeile/agreedisclaimer/tree/0.1.1

This branch still has some debug messages, which I will remove in approx. six hours from now. You may test it an see if it is working.

Please also note that this branch has a new feature:
* One time sign-in, which work by using cookies. The feature must be enabled on the admin page.

I would appreciate if you give me some feedback.

Best regards
Josef

**Comment by jmeile** [comment]
It turns out that this issue was still present on OwnCloud standard installations where the domain had the form: https://my_domain/owncloud. On my case, I only had: https://my_domain

So, it worked for me, but for others didn't. This is fixed on branch 1.0.2
